# Setup
path:         ""
baseurl:      ""
markdown:     kramdown
google_analytics: 
github:       ipld/ipld.io

# Metadata
title:        IPLD
description:  InterPlanetary Linked Data
license:      MIT

# Favicon
favicon:
  mimetype:   image/png
  name:       favicon.png

# Logo
# The mimetype is defined by OGP. See http://ogp.me
# Comment out all of these lines to use title and description in the header
# logo:
#   name:       caiman.png
#   mimetype:   image/png
#   width:      800
#   height:     800

# About/contact
author:
  name:       Protocol Labs
  url:        http://ipfs.io

# Open Source Protocol
# See http://osprotocol.com
os:
  repo:     https://github.com/ipld/ipld.io
  src:      git@github.com:ipld/ipld.io.git
  issues:   https://github.com/ipld/ipld.io/issues
  branch:   master
  rcs_type: git

# Maintainer (normally on GitHub)
maintainer:
  name: RichardLitt
  link: https://github.com/RichardLitt

# Gems
